package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer id;
     private String city;
     private String street;
     private String homeNumber;
     private Set persons = new HashSet(0);

    public Address() {
    }

    public Address(String city, String street, String homeNumber, Set persons) {
       this.city = city;
       this.street = street;
       this.homeNumber = homeNumber;
       this.persons = persons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getHomeNumber() {
        return this.homeNumber;
    }
    
    public void setHomeNumber(String homeNumber) {
        this.homeNumber = homeNumber;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }




}


