package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private Publisher publisher;
     private String name;
     private String author;
     private Integer price;
     private Integer year;
     private Set borrowbooks = new HashSet(0);

    public Book() {
    }

	
    public Book(Category category, Publisher publisher) {
        this.category = category;
        this.publisher = publisher;
    }
    public Book(Category category, Publisher publisher, String name, String author, Integer price, Integer year, Set borrowbooks) {
       this.category = category;
       this.publisher = publisher;
       this.name = name;
       this.author = author;
       this.price = price;
       this.year = year;
       this.borrowbooks = borrowbooks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Publisher getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(Publisher publisher) {
        this.publisher = publisher;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public Set getBorrowbooks() {
        return this.borrowbooks;
    }
    
    public void setBorrowbooks(Set borrowbooks) {
        this.borrowbooks = borrowbooks;
    }




}


