package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Borrowlist generated by hbm2java
 */
public class Borrowlist  implements java.io.Serializable {


     private Integer id;
     private Reader reader;
     private Staff staff;
     private Integer amount;
     private Set borrowbooks = new HashSet(0);

    public Borrowlist() {
    }

	
    public Borrowlist(Reader reader) {
        this.reader = reader;
    }
    public Borrowlist(Reader reader, Staff staff, Integer amount, Set borrowbooks) {
       this.reader = reader;
       this.staff = staff;
       this.amount = amount;
       this.borrowbooks = borrowbooks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Reader getReader() {
        return this.reader;
    }
    
    public void setReader(Reader reader) {
        this.reader = reader;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
    public Set getBorrowbooks() {
        return this.borrowbooks;
    }
    
    public void setBorrowbooks(Set borrowbooks) {
        this.borrowbooks = borrowbooks;
    }




}


