package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1



/**
 * Borrowbook generated by hbm2java
 */
public class Borrowbook  implements java.io.Serializable {


     private Integer id;
     private Book book;
     private Borrowlist borrowlist;
     private int quantity;

    public Borrowbook() {
    }

    public Borrowbook(Book book, Borrowlist borrowlist, int quantity) {
       this.book = book;
       this.borrowlist = borrowlist;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Borrowlist getBorrowlist() {
        return this.borrowlist;
    }
    
    public void setBorrowlist(Borrowlist borrowlist) {
        this.borrowlist = borrowlist;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


