package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private String nameCate;
     private String des;
     private Set books = new HashSet(0);

    public Category() {
    }

    public Category(String nameCate, String des, Set books) {
       this.nameCate = nameCate;
       this.des = des;
       this.books = books;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNameCate() {
        return this.nameCate;
    }
    
    public void setNameCate(String nameCate) {
        this.nameCate = nameCate;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


