package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fullname generated by hbm2java
 */
public class Fullname  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Set persons = new HashSet(0);

    public Fullname() {
    }

    public Fullname(String firstName, String lastName, Set persons) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.persons = persons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }




}


