package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer id;
     private Address address;
     private Fullname fullname;
     private String tel;
     private String des;
     private Set accounts = new HashSet(0);
     private Staff staff;
     private Reader reader;

    public Person() {
    }

	
    public Person(Address address, Fullname fullname) {
        this.address = address;
        this.fullname = fullname;
    }
    public Person(Address address, Fullname fullname, String tel, String des, Set accounts, Staff staff, Reader reader) {
       this.address = address;
       this.fullname = fullname;
       this.tel = tel;
       this.des = des;
       this.accounts = accounts;
       this.staff = staff;
       this.reader = reader;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public Fullname getFullname() {
        return this.fullname;
    }
    
    public void setFullname(Fullname fullname) {
        this.fullname = fullname;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Reader getReader() {
        return this.reader;
    }
    
    public void setReader(Reader reader) {
        this.reader = reader;
    }




}


