package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Publisher generated by hbm2java
 */
public class Publisher  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String hotline;
     private String address;
     private Set books = new HashSet(0);

    public Publisher() {
    }

    public Publisher(String name, String hotline, String address, Set books) {
       this.name = name;
       this.hotline = hotline;
       this.address = address;
       this.books = books;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getHotline() {
        return this.hotline;
    }
    
    public void setHotline(String hotline) {
        this.hotline = hotline;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }




}


