package com.vanhy.entity;
// Generated May 25, 2018 8:48:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private int personId;
     private Person person;
     private String codeStaff;
     private String position;
     private Set borrowlists = new HashSet(0);

    public Staff() {
    }

	
    public Staff(Person person) {
        this.person = person;
    }
    public Staff(Person person, String codeStaff, String position, Set borrowlists) {
       this.person = person;
       this.codeStaff = codeStaff;
       this.position = position;
       this.borrowlists = borrowlists;
    }
   
    public int getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(int personId) {
        this.personId = personId;
    }
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }
    public String getCodeStaff() {
        return this.codeStaff;
    }
    
    public void setCodeStaff(String codeStaff) {
        this.codeStaff = codeStaff;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public Set getBorrowlists() {
        return this.borrowlists;
    }
    
    public void setBorrowlists(Set borrowlists) {
        this.borrowlists = borrowlists;
    }




}


